### ISSUE TITLE
Issue with CloudWatch VPC Endpoint Configuration 

### ISSUE THREAD

**Issue by mayank0202** [sourcefuse/terraform-aws-arc-network#60]
I ran into this issue while attempting to the use the option for the cloudwatch VPC endpoint in our nework module. Example setting:

```
vpc_endpoint_config = {
    s3         = true
    kms        = true
    cloudwatch = true
    elb        = true
    dynamodb   = true
    ec2        = false
    sns        = true
    sqs        = true
  }
```
Everything works as expected, except for how the underlying CP module works
- Pulls in the default SG for a VPC and assigns it to the VPC endpoint
- We aren't exposing the configuration options that are needed by the CP module to properly configure
- https://github.com/cloudposse/terraform-aws-vpc/blob/2.1.0/modules/vpc-endpoints/main.tf#L27

```
# Because security group ID may not be known at plan time, we cannot use it as a key
  security_group_associations_list = flatten([for k, v in var.interface_vpc_endpoints : [
    for i, s in v.security_group_ids : {
      key               = "${k}[${i}]"
      index             = i
      interface         = k
      security_group_id = s
    }
  ]])

  security_group_associations_map = { for v in local.security_group_associations_list : v.key => v }
```

For the VPC endpoints, we can test that
```
Task stopped at: 2023-10-09T20:15:54.334Z
ResourceInitializationError: failed to validate logger args: create stream has been retried 7 times: failed to create Cloudwatch log stream: RequestError: send request failed caused by: Post "https://logs.us-east-1.amazonaws.com/": dial tcp: lookup logs.us-east-1.amazonaws.com on 10.19.0.2:53: no such host : exit status 1
```

Once the VPC endpoints are up, they will resolve to IPs in the CIDR range of the VPC

Expected Behaviour 💯 

For the ARC IaC reference architecture, I am fine with creating a VPC endpoint SG that is open to the VPC cidr block

**Comment by vijay-stephen** [comment]
This issue is closed because Module has been refactored
